sudo: false
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
install: pip install -U tox-travis
script: tox

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
