site_name: parglare

site_description: A pure Python (G)LR parser with integrated scanner
site_author: Igor Dejanović

repo_url: https://github.com/igordejanovic/parglare
google_analytics: ['UA-68681917-1', 'igordejanovic.net']
theme: readthedocs
extra_css: ['style.css']

pages:
- Home: index.md
- User Guide:
    - Getting started: getting_started.md
    - Grammar: grammar.md
    - Parser parameters: parser.md
    - Actions: actions.md
    - Recognizers: recognizers.md
    - Conflicts resolving: conflicts.md
    - Parse trees: parse_trees.md
    - Error recovery: recovery.md
    - pglr command: pglr.md
    - Debugging: debugging.md
- About:
    - Contributing: about/CONTRIBUTING.md
    - License: about/LICENSE.md

markdown_extensions:
    - admonition:
    - toc:
        permalink: True

copyright: Copyright &copy; 2017 <a href="http://igordejanovic.net/">Igor Dejanović</a>.
