site_name: parglare

site_description: A pure Python (G)LR parser with integrated scanner
site_author: Igor Dejanović

repo_url: https://github.com/igordejanovic/parglare
google_analytics: ['UA-68681917-1', 'igordejanovic.net']
theme: readthedocs

pages:
- Home: index.md
- User Guide:
    - Grammar: grammar.md
- About:
    - Contributing: ../CONTRIBUTING.md
    - License: ../LICENSE

markdown_extensions:
    - admonition:
    - toc:
        permalink: True

copyright: Copyright &copy; 2017 <a href="http://igordejanovic.net/">Igor Dejanović</a>.
